version: '3.7'

services:
  vue:
    container_name: vue-container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
<<<<<<< HEAD
      - '8081:8080'
=======
      - '8080:8080'
>>>>>>> a5a674a (starting 2 app with docker)
